version: "3.8"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sdc_root_password
      MYSQL_DATABASE: sdc
      MYSQL_USER: sdc
      MYSQL_PASSWORD: sdc_password
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  db:
