name: Read Events Table Every 12 Hours

# Description: 
# We need the planet scale db alive. 
# - So this just calls the events page every week to do that.
# - For context, planetscale's free tier shuts down after
#   - 7 days of inactivity.
# Run every 12 Hours

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  
jobs:
  db-read:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Next.js API
        run: curl curl https://sdc-v3.vercel.app/events